# Generated by Django 5.0.2 on 2024-03-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='land_photo',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.AddField(
            model_name='property',
            name='about_builder',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='property',
            name='area_range_sqft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='bhk_range',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='brief_about_property',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='property',
            name='builder_name',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='city_name',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='floor_plan',
            field=models.ImageField(default='NA', upload_to='floor_plans/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ImageField(default='NA', upload_to='property_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='property_name',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
